config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :households, only: [:show]

  devise_for :users, :path_prefix => 'auth'
  resources :users, except: [:index]

  resources :menus, only: [:index, :show, :new] do
    resources :meals, only: [:show] do
      resources :courses, only: [:destroy]
    end
  end

  resources :menus, only: [] do
    member do
      get ':meal_type', to: 'menus#show_meal', as: 'show_meal'
    end
  end

  resources :courses, only: [:index] do
    collection do
      post 'create', to: 'courses#create', as: 'create'
      delete 'multi_destroy', to: 'courses#multi_destroy', as: 'multi_destroy'
    end
  end

  resources :planners, only: [:index, :new, :create]

  resources :recipes, only: [:index, :show] do
    collection do
      get 'recipe_search'
    end
  end

  resources :fetch_recipes, only: [:index] do
    post 'search'
  end

  resources :groceries, only: [:index, :new, :create] do
    collection do
      patch 'edit_multiple', to: 'groceries#edit_multiple', as: 'edit_multiple'
    end
  end

  # resources :products, only: [:index]
end

app/models/menu.rb
class Menu < ApplicationRecord
  after_create :create_menu_meals

  belongs_to :household

  has_many :meals, dependent: :destroy
  has_many :groceries

  validates :date, presence: true

  scope :ordered, -> { order(date: :asc) }


  def day_of_week
    "#{self.date.strftime('%a')}: #{self.date.day.ordinalize}  "
  end

  private

  def self.calendar
    (Date.current...(Date.current + 10))
  end

  def self.create_menus(household)
    calendar = Menu.calendar
    menu_count = Menu.where('household_id = ?', household).where('date IN (:cal)', { cal: calendar }).count
    if menu_count >= calendar.count
      @menus = Menu.where('household_id = ?', household).where('date IN (:cal)', { cal: calendar }).ordered
    else
      cal_menu = Menu.where('household_id = ?', household).where('date IN (:cal)', { cal: calendar }).ordered
      menu_dates = cal_menu.map { |d| d.date }
      menu_dates_missing = calendar.select { |d| d if menu_dates.exclude?(d) }
      menu_dates_missing.each { |d| Menu.create!(date: d, household_id: household.id) }
      @menus = Menu.where('household_id = ?', household).where('date IN (:cal)', { cal: calendar }).ordered
    end
  end

  def create_menu_meals
    menu = self
    household = Household.find(menu.household_id)
    users = household.users
    meal_types = Meal::MEAL_TYPES
    users.each do |user|
      meal_types.each do |meal_type|
        Meal.create!(menu: menu, user: user, meal_type: meal_type)
      end
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  SEARCH_CRITERIA = {
    MEAL_TYPES: Meal::MEAL_TYPES,
    COURSE_TYPES: Course::COURSE_TYPES,
    DIETARY_FILTERS: ["vegan", "vegetarian", "paleo"]
  }

  # size options = THUMBNAIL, SMALL & REGULAR
  def recipe_image( attr = {})
    sz = attr[:size].upcase
    images[sz]["url"]
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_meal_types, only: [:index, :recipe_search]
  before_action :set_course_types, only: [:index, :recipe_search]
  before_action :set_dietary_filters, only: [:index, :recipe_search]
  before_action :set_recipe, only: [:show]


  def index
    s = { query: ["peanut butter"],
          filters: { mealType: "",
                     dishType: "",
                     health: "" } }
    results = Edamam::EdamamRecipe.search(s[:query], s[:filters])
    if results.keys.include?(:Status)
      redirect_to root_path, notice: "Recipe API error: " + @results
    else
      @recipes = results[:recipes]
      @next_page = results[:next_page] unless results[:next_page].nil?
    end
  end

  def show
  end

  def recipe_search
    query = params[:query]
    filters = params[:filters]
      unless filters["dishType"].empty?
        course_type = filters['dishType']
        dish_types = Course::DISH_TYPES[course_type.to_sym]
        filters["dishType"] = dish_types
      end
    results = Edamam::EdamamRecipe.search(query, filters)
    if results.keys.include?(:Status)
      redirect_to root_path, notice: "Recipe API error: " + @results
    else
      @recipes = results[:recipes]
      @next_page = results[:next_page] unless results[:next_page].nil?
    end

    @title = params[:title]
    @course_type = params[:course_type].nil? ? params[:filters][:dishType] : params[:course_type]

    # Meal Planner params
    if params["meal_ids"].present?
      @meal_ids = params["meal_ids"]
    elsif params["menu_id"].present?
      @menu = Menu.find(params["menu_id"].to_i)
      @meal = Meal.find(params["meal_id"].to_i)
    end
  end

  private

  def set_meal_types
    @meal_types = Meal::MEAL_TYPES
  end

  def set_course_types
    @course_types = Course::COURSE_TYPES
  end

  def set_dietary_filters
    @dietary_filters = Health::HEALTH_TYPES
  end

  def set_recipe
    recipe_id = params[:id]
    @result = Edamam::EdamamRecipe.find(recipe_id)
    if @result.instance_of?(Recipe)
      @recipe = @result
    else
      redirect_to root_path, notice: "Recipe API error: " + @result
    end
  end
end

app/views/recipes/_load_more.html.erb
  <%# <%= render partial: "/recipes/load_more"%> %>


<% if @next_page[:links].nil? %>
  <% href = "" %>
  <% count = "" %>
  <% total = "" %>
<% else %>
  <% href = @next_page[:links][:href] %>
  <% count = @next_page[:count] %>
  <% total = @next_page[:total] %>
<% end %>

<% yield(:title).blank? ? title = title : title = yield(:title) %>
<div id="load_more" >
    <div class="load_recipes ">
      <%= link_to "Next Page", fetch_recipe_search_path(total: total, href: href, count: count, title: title),
            class: "btn btn--dark btn--go",
            data: { turbo_method: :post,
                    target: 'infinite-scroll.pagination' }   %>
    </div>
</div>

app/views/recipes/_recipe-card.html.erb
<% @recipes.each do |r| %>
  <div class="recipe-card">
    <div class="card-header">
    <%= image_tag (r.image), size: "100" %>
    </div>
    <div class="card-body">
      <p><small>Name:<%= r.label %></small>
      <small> Source:<%= r.source %></small>
      <small> Servings:<%= r.yield %></small></p>
    </div>
    <div class="card-footer">
      <%= link_to 'Recipe Details', recipe_path("#{r.erecipe_id}") %>

      <p><font size="1">ID: <%= r.erecipe_id %></font></p>
    </div>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="card-recipe" data-controller="visability">
  <div class="card-recipe__header hideable-flex" data-visability-target="hideableFlex">
      <p class="label"><%= recipe.label %></p>
      <p class="source"><%= recipe.source %></p>
      <%= link_to (image_tag recipe.recipe_image(size: "regular")), recipe.source_url,
          target: '_blank'
      %>
  </div>
  <div class="card-recipe__footer hideable-flex flex-collapsed" data-visability-target="hideableFlex">
    <div class="list">
      <% recipe.ingredients.each do |i| %>
        <div class="item">&bull; <%= i['text']%></div>
      <% end %>
    </div>
  </div>
  <div class="card-recipe__body">
    <div class="content-header hideable-div div-hidden" data-visability-target="hideableDiv">
      <%= link_to recipe.label, recipe.source_url, target: '_blank' %>
      <p><%= recipe.source %></p>
    </div>
    <div class="content-body">
      <ul class="details">
        <li class="item servings">
          <i class="fa-solid fa-user"></i>
          <span class="value"><%= recipe.yield %></span>
          <span class="title hideable-div" data-visability-target="hideableDiv">Servings</span>
        </li>
        <li class="item ingredients">
          <i class="fa-solid fa-book-open"></i>
          <span class="value"><%= recipe.ingredients.count %></span>
          <span class="title hideable-div" data-visability-target="hideableDiv">Ingredients</span>
        </li>
      </ul>
      <button data-action="visability#toggleTargets"></button>
    </div>
  </div>
  <div class="form-button">
    <%= recipe_form(page_title: locals[:title], erecipe_id: recipe.erecipe_id) %>
  </div>
</div>

app/views/recipes/_recipes.html.erb
<%= turbo_frame_tag "recipes", class: "section--cards section--cards-recipes",
    target: "_top" do %>
  <div id="recipe_cards" class="card-rolodex">
    <%= render recipes, locals: { title: yield(:title) } %>
  </div>

  <%= turbo_frame_tag "fetch-recipes",
    src: fetch_recipes_path(href: @next_page[:links][:href],
                              title: yield(:title),
                              count: @next_page[:count],
                              total: @next_page[:total],
                              format: :turbo_stream),
    loading: :lazy do %>
    Fetching more recipes .... ... .. .
  <% end %>
  <div id="apply_course" data-course-new-form-target="newRecipes"></div>
  <div id="gList"></div>
<% end %>

app/views/recipes/_search_form.html.erb
<%= form_with(url: recipe_search_recipes_path, method: "GET", class:"search-bar", data: {turbo_frame: "recipes" }) do |f| %>
    <% title = yield :title %>
  <%= f.fields_for :filters do |ft| %>
    <%= ft.hidden_field :mealType, name:"[filters][mealType]",
                        value: @meal_type,
                        data: { target: 'recipe-search-filter.mealSearchFilter' } %>
    <%= ft.hidden_field :dishType, name:"[filters][dishType]",
                        value: @course_type,
                        data: { target: 'recipe-search-filter.courseSearchFilter' }  %>
    <%= ft.hidden_field :health, name:"[filters][health][]", multiple: true,
                        value: @dietary_restrictions,
                        data: { target: 'recipe-search-filter.healthSearchFilter' } %>
    <div class="filters-section">
      <div class="filtered filtered--vert-ctr filtered--hrzn-r">
        <ul class="filtered__list filtered__list--hrzn-r filtered__list--nowrap">
          <%= filter_dietary(dietary: @dietary_restrictions) %>
        </ul>
      </div>
    </div>
  <% end %>
    <div class="bar">
      <%= f.text_field :query, multiple: true, class: "input", placeholder: "Enter ingredient or recipe name" %>
      <%= button_tag type: 'submit', class: "btn btn--light btn--go" do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    </div>

  <%# Send info to recipe#search controller for recipe rendering %>
  <%= hidden_field_tag :title, yield(:title) %>
  <% if title == "Meal Planner" %>
      <div class="bar-footer">
      <%= link_to "Done Planning", menus_path, class: "btn btn--light btn--stop" %>
    </div>

    <%= hidden_field_tag 'course_type', @course_type, data: { target: 'course-new-form.formCourseType' } %>
  <% end %>


  <% if @meal_ids.present? %>
    <%= hidden_field_tag 'meal_ids', @meal_ids %>
  <% elsif @meal.present? %>
    <%= hidden_field_tag 'meal_id', @meal.id %>
    <%= hidden_field_tag 'menu_id', @menu.id %>
    <%= hidden_field_tag 'course_id', @course.id %>
  <% end %>
<% end %>

app/views/recipes/index.html+turbo_frame.erb
<%= render "recipes", recipes: @recipes, locals: { title: yield(:title) } %>

  <%= turbo_frame_tag "fetch-recipes",
    src: fetch_recipes_path(href: @next_page[:links][:href],
                              title: @title,
                              count: @next_page[:count],
                              total: @next_page[:total],
                              format: :turbo_stream),
    loading: :lazy do %>
    Fetching more recipes .... ... .. .
  <% end %>

app/views/recipes/index.html.erb
<%- title "Recipes" %>
<div class="body body--recipes"
      id="<%= yield(:title) %>"
      data-controller="recipe-search-filter"
      >
  <%= render 'shared/searchbar' %>
  <%= render 'shared/sidebar' %>
  <%= render "recipes", recipes: @recipes, locals: { title: yield(:title) } %>
</div>

app/views/recipes/recipe_search.html+turbo_frame.erb
<%= turbo_frame_tag "recipes", class: "section--cards section--cards-recipes",
    target: "_top" do %>
  <div id="recipe_cards" class="card-rolodex">
    <%= render @recipes, locals: { title: @title }  %>
  </div>

  <%= turbo_frame_tag "fetch-recipes",
    src: fetch_recipes_path(href: @next_page[:links][:href],
                              title: @title,
                              count: @next_page[:count],
                              total: @next_page[:total],
                              format: :turbo_stream),
    loading: :lazy do %>
    Fetching more recipes .... ... .. .
  <% end %>
  <div id="apply_course" data-course-new-form-target="newRecipes"></div>
  <div id="gList"></div>
<% end %>

app/views/recipes/show.html.erb
<%- title "Recipe" %>

<div class="body">
  <div class="section--header">
  <h1>Recipes Show page</h1>
  </div>
  <div class="section-cards">
    <div class="card-deck">

        <div class="card-recipe">
          <div class="card-recipe-show__body">
            <div class="content-header">
              <p><%= @recipe.label %></p>
              <p><%= @recipe.source %></p>
            </div>
            <div class="content-body">
              <ul class="details">
                <li class="item">
                  <i class="fa-solid fa-user"></i>
                  <span class="value"><%= @recipe.yield %></span>
                </li>
                <li class="item">
                  <i class="fa-solid fa-book-open"></i>
                  <span class="value"><%= @recipe.ingredients.count %></span>
                </li>
              </ul>
              <%= link_to "", recipe_path(@recipe.erecipe_id) %>
            </div>
          </div>
          <div class="card-recipe-show__footer">
            <ul class="list">
              <% @recipe.ingredients.each do |i| %>
                <li><%= i['text'] %></li>
              <% end %>
            </ul>
          </div>
        </div>

    </div>
  </div>

</div>