config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :households, only: [:show]

  devise_for :users, :path_prefix => 'auth'
  resources :users, except: [:index]

  resources :menus, only: [:index, :show, :new] do
    resources :meals, only: [:show] do
      resources :courses, only: [:destroy]
    end
  end

  resources :menus, only: [] do
    member do
      get ':meal_type', to: 'menus#show_meal', as: 'show_meal'
    end
  end

  resources :courses, only: [:index] do
    collection do
      post 'create', to: 'courses#create', as: 'create'
      delete 'multi_destroy', to: 'courses#multi_destroy', as: 'multi_destroy'
    end
  end

  resources :planners, only: [:index, :new, :create]

  resources :recipes, only: [:index, :show] do
    collection do
      get 'recipe_search'
    end
  end

  resources :fetch_recipes, only: [:index] do
    post 'search'
  end

  resources :groceries, only: [:index, :new, :create] do
    collection do
      patch 'edit_multiple', to: 'groceries#edit_multiple', as: 'edit_multiple'
    end
  end

  # resources :products, only: [:index]
end

app/views/shared/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<%# <%= message %> %>

app/views/shared/_header.html.erb
<div class="header">


</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <ul class="navbar__nav">
    <li class="navbar__brand navbar__border nav-btn
              <%= active_page(path: root_path, class_name: 'nav-active') %>">

        <i class="fa-regular fa-calendar-days"> <%= link_to "", root_path %> </i>

    </li>
  <% if user_signed_in? %>
    <li class="navbar__item navbar__border nav-btn
              <%= active_page(path: menus_path, class_name: 'nav-active') %>
              <%= active_page(path: planners_path, class_name: 'nav-active') %>">
      <%= link_to "Menu", menus_path%>
    </li>
    <li class="navbar__item navbar__border nav-btn
              <%= active_page(path: recipes_path, class_name: 'nav-active') %>">
      <%= link_to "Recipes", recipes_path %>
    </li>
    <li class="navbar__item navbar__border nav-btn
              <%= active_page(path: groceries_path, class_name: 'nav-active') %>">
      <%= link_to "Grocery List", groceries_path %>
    </li>
    <li class="navbar__item navbar__border nav-btn
                <%= active_page(path: household_path(current_user.household_id), class_name: 'nav-active') %>">
      <%= link_to "Household", household_path(current_user.household_id) %>
    </li>
    <li class="dropdown navbar__border
      <%# active_page(path: household_path(current_user.household_id), class_name: 'nav-active')  %>
    ">
      <a href="#"
          class="avatar navbar__dropdown nav-btn"
        id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa-solid fa-bars"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <p>Welcome back <%= current_user.name_first %></p>
         <%# link_to "Household", household_path(current_user.household_id) , class: "dropdown-item"  %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class: "dropdown-item" %>
      </div>
    </li>
  <% else %>
    <li class="navbar__item navbar__border nav-btn">
      <%= link_to "Menu has many Meals", "#", class: "nav-link" %>
    </li>
    <li class="dropdown navbar__border">
      <a href="#"
          class="avatar navbar__dropdown nav-btn"
        id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa-solid fa-bars"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <p>Welcome to mhmm</p>
        <p>About Us (link)</p>
      </div>
    </li>
  <% end %>
  </ul>
</div>

app/views/shared/_searchbar.html.erb
<div class="section--searchbar">
  <% title = yield :title %>
  <div class="section--searchbar__title">
    <%# Helper insert %>
    <div class="title">
      <% if title == "Meal Planner" %>
        <h2>Meal Planner for:</h2>
        <% end %>
      <% if title == "Recipes" %>
        <h2>Search for Recipes:</h2>
      <% end %>
    </div>
  </div>
  <div class="section--searchbar__bar">
    <%= render 'recipes/search_form' %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">

   <% title = yield :title %>
    <% if title == "Meal Planner" %>
      <div class="sidebar__filters filters-section">
        <div class="filtered">
          <div class="filtered__title filtered__title-light">
            <h3>Household diners:</h3>
          </div>
          <ul class="filtered__list">
                  <%= filter_users(users: @users) %>
                  <%= filter_users(users: @user) %>
          </ul>
        </div>
        <div class="filtered">
          <div class="filtered__title filtered__title-light">
            <h3>Dates:</h3>
          </div>
          <ul class="filtered__list">
              <%= filter_dates(dates: @menus) %>
          </ul>
          <ul class="filtered__list">
              <%= filter_types(type: @meal_type) %>
          </ul>


        </div>
      </div>
      <div class="sidebar__planner">
        <div class="filtered">
          <div class="filtered__title filtered__title-light">
            <h3>Select courses for <%= @users.count * @menus.count %> Servings of</h3>
          </div>

          <ul class="filtered__list">
            <%= select_radio_course_types(course_types: @course_types)  %>
          </ul>
        </div>
        <div class="footer">
          <div id="refreshCourses"></div>
        </div>
      </div>
      <div class="sidebar__courses ">
         <div class="sidebar__courses-header">
          <h3>Selected Courses:</h3>
        </div>
        <div class="sidebar__courses-content">
          <%= turbo_frame_tag id="courses", class: "section--cards-courses",
                        src: courses_path(meal_ids: @meal_ids),
                        data: { refresh_frame_target: "plannerCourses" } %>
        </div>
      </div>
    <% end %>



    <% if title == "Recipes" %>
      <div class="sidebar__filters filters-section">
        <div class="filtered">
          <div class="filtered__title filtered__title-light">
            <h3>Select Meal type to filter</h3>
          </div>
          <ul class="filtered__list">
            <%= select_radio_meal_types(meal_types: @meal_types)  %>
          </ul>
        </div>
        <div class="filtered">
          <div class="filtered__title filtered__title-light">
            <h3>Select Course type to filter</h3>
          </div>
          <ul class="filtered__list">
            <%= select_radio_course_types(course_types: @course_types)  %>
          </ul>
        </div>
        <div class="filtered">
          <div class="filtered__title filtered__title-light">
            <h3>Select Dietary Restrictions to filter</h3>
          </div>
          <ul class="filtered__list">
            <%= select_checkbox_health_types(dietary_filters: @dietary_filters)  %>
          </ul>
        </div>
      </div>
    <% end %>
</div>