config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :households, only: [:show]

  devise_for :users, :path_prefix => 'auth'
  resources :users, except: [:index]

  resources :menus, only: [:index, :show, :new] do
    resources :meals, only: [:show] do
      resources :courses, only: [:destroy]
    end
  end

  resources :menus, only: [] do
    member do
      get ':meal_type', to: 'menus#show_meal', as: 'show_meal'
    end
  end

  resources :courses, only: [:index] do
    collection do
      post 'create', to: 'courses#create', as: 'create'
      delete 'multi_destroy', to: 'courses#multi_destroy', as: 'multi_destroy'
    end
  end

  resources :planners, only: [:index, :new, :create]

  resources :recipes, only: [:index, :show] do
    collection do
      get 'recipe_search'
    end
  end

  resources :fetch_recipes, only: [:index] do
    post 'search'
  end

  resources :groceries, only: [:index, :new, :create] do
    collection do
      patch 'edit_multiple', to: 'groceries#edit_multiple', as: 'edit_multiple'
    end
  end

  # resources :products, only: [:index]
end

app/models/household.rb
class Household < ApplicationRecord
  after_create :generate_menus

  has_many :users, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many :groceries, dependent: :destroy

  def generate_menus
    household = self
    Menu.create_menus(household)
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :menu
  belongs_to :user

  has_many :courses, dependent: :destroy

  validates :meal_type, presence: true

  MEAL_TYPES = [
    "breakfast",
    "lunch",
    "dinner"
  ]

  def self.meals(attr = {})
    @menus = attr[:menus]
    @users = attr[:users]
    @meal_type = attr[:meal_type]
    meals = []
    @menus.each do |menu|
      @users.each do |user|
        meal = where('user_id = ?', user.id).where('menu_id = ?', menu.id).where('meal_type = ?', @meal_type).ids
        meals.push(meal)
      end
    end
    meals.flatten.map { |meal| Meal.find(meal) }
  end

  def self.meal_ids(attr = {})
    menus = attr[:menus]
    users = attr[:users]
    meal_type = attr[:meal_type]
    meal_ids = []
    menus.each do |menu|
      users.each do |user|
        id = where('user_id = ?', user.id).where('menu_id = ?', menu.id).where('meal_type = ?', meal_type).ids
        meal_ids.push(id)
      end
    end
    meal_ids.flatten
  end
end

app/models/meal/multicourse.rb
class Meal::Multicourse
  def self.create(course_params)
    new(course_params).create(course_params)
  end

  def initialize(course_params)
    @meals = course_params[:meal_ids].first.split.map { |id| Meal.find(id.to_i) }
    #  course_type needs to be predetermined on Meal page
    @course_type = course_params[:course_type]
    @erecipe_id = course_params[:erecipe_id]
  end

  def create(course_params)
    validate_params!

    @course_count = @meals.count
    @new_courses = 0
    @courses = []
    @meals.each do |meal|
      @courses.push(Course.create!(course_type: @course_type, erecipe_id: @erecipe_id, meal: meal))
      @new_courses += 1
    end
    @courses
  end


  def validate_params!
    raise "Invalid params" unless @meals.present?
    raise "Invalid params" unless @course_type.present?
    raise "Invalid params" unless @erecipe_id.present?
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  after_create :create_menu_meals

  belongs_to :household

  has_many :meals, dependent: :destroy
  has_many :groceries

  validates :date, presence: true

  scope :ordered, -> { order(date: :asc) }


  def day_of_week
    "#{self.date.strftime('%a')}: #{self.date.day.ordinalize}  "
  end

  private

  def self.calendar
    (Date.current...(Date.current + 10))
  end

  def self.create_menus(household)
    calendar = Menu.calendar
    menu_count = Menu.where('household_id = ?', household).where('date IN (:cal)', { cal: calendar }).count
    if menu_count >= calendar.count
      @menus = Menu.where('household_id = ?', household).where('date IN (:cal)', { cal: calendar }).ordered
    else
      cal_menu = Menu.where('household_id = ?', household).where('date IN (:cal)', { cal: calendar }).ordered
      menu_dates = cal_menu.map { |d| d.date }
      menu_dates_missing = calendar.select { |d| d if menu_dates.exclude?(d) }
      menu_dates_missing.each { |d| Menu.create!(date: d, household_id: household.id) }
      @menus = Menu.where('household_id = ?', household).where('date IN (:cal)', { cal: calendar }).ordered
    end
  end

  def create_menu_meals
    menu = self
    household = Household.find(menu.household_id)
    users = household.users
    meal_types = Meal::MEAL_TYPES
    users.each do |user|
      meal_types.each do |meal_type|
        Meal.create!(menu: menu, user: user, meal_type: meal_type)
      end
    end
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal_types, only: [:show]
  before_action :set_course_types, only: [:show]
  before_action :set_household
  before_action :set_menu, only: [:show]
  before_action :set_meal, only: [:show]
  before_action :set_user, only: [:show]


  def show
    @meal_ids = []
    @meal_ids.push(@meal.id.to_s)
    @courses = @meal.courses
    @recipes = @courses.map { |course| Edamam::EdamamRecipe.find(course.erecipe_id) }

    console
  end

  private

  def set_meal_types
    @meal_types = Meal::MEAL_TYPES
  end

  def set_course_types
    @course_types = Course::COURSE_TYPES
  end

  def set_household
    @household = Household.find(current_user.household_id)
  end

  def set_menu
    @menu = Menu.find(params[:menu_id])
  end

  def set_meal
    @meal = @menu.meals.find(params[:id])
  end

  def set_user
    @user = @meal.user
  end
end

app/views/meals/_meal.html.erb
<div class= "card-meal" data-controller="refresh-frame">
  <% @meal = meal %>
  <div class="card-meal__header">

    <h4><%= User.find(@meal.user_id).name_first %></h4>
    <%= link_to planners_path(  meal_ids: [@meal.id]),
                                data: { turbo_frame: "_top" } do %>
      <i class="btn--edit fa-solid fa-pen-to-square"></i>
    <% end %>
  </div>
  <div class="card-meal__body">

  <%= turbo_frame_tag id="courses", class: "section--cards-courses",
                src: courses_path(meal_ids: [@meal.id]),
                data: { refresh_frame_target: "plannerCourses" } %>

  <%# Go through each course (@courses) and match course_type & render card %>
  </div>
  <div class="card-meal__footer">
    <div id="refreshCourses"></div>
  </div>
</div>

app/views/meals/_new.html.erb
<%= form_with url: "/meals", method: :post do |f| %>
  <div class="mb-3">
  <%= f.collection_check_boxes :menu_ids, @menus, :id, :date, include_hidden: false %>
  </div>
  <div class="mb-3">
  <%= f.collection_check_boxes :user_ids, @users, :id, :name_first, include_hidden: false %>
  </div>
  <div class="mb-3">
  <%= f.select :meal_type, collection: @meal_type %>
  </div>
  <div class="mb-3">
  <%= f.submit %>
  </div>
<% end %>

app/views/meals/_new_meal.html.erb
  <div data-controller="meal-new">
    <%= form_with url: "/meals/new", method: 'get' do |f| %>
      <div class="mb-3" data-meal-new-target="getType">
        <%= f.select :meal_types, @meal_types, { prompt: "Select meal" } %>
      </div>
      <div class="mb-3" data-meal-new-target="getUserID">
        <%= f.collection_check_boxes(:user_ids, @users, :id, :name_first, include_hidden: false) %>
      </div>
      <div class="mb-3" data-meal-new-target="getMenuID">
        <%= f.collection_check_boxes(:menu_ids, @menus, :id, :day_of_week, include_hidden: false) %>

      </div>
        <%= f.submit "Next" %>
    <% end %>
      <%# <%= link_to "Finish Meal", "#", data: { action: "click->meal-new#setMeal" } %>
    <div class="card-footer text-muted mt-2" data-meal-new-target="errorMessage" >
    </div>
  </div>

app/views/meals/_recipe.html.erb
<% @recipes.each do |r| %>
  <div class="recipe-card">
    <div class="text-center">
      <%= image_tag recipe.image, size: "100" %>
    </div>
    <div class="card-body">
      <ul>
        <li>Name: <%= link_to recipe.label, recipe_path(recipe.erecipe_id  ) %></li>
        <li>Source: <%= recipe.source %></li>
        <li>Servings: <%= recipe.yield %></li>
      </ul>
    </div>
    <div class="card-footer">
      <%= form_with url: meals_path do |f| %>
        <%# <%= f.hidden_field :erecipe_id, value: recipe.erecipe_id %> %>
        <%= f.hidden_field :course_type, value: params[:filters][:dishType] %>
        <%= f.hidden_field :meal_ids, name:"meal_ids[]", mutliple: true, value: @meals %>
        <%= f.submit "Add Course" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/meals/new.html.erb
<%- title "Multi-Meal" %>

<div class="container">
  <div class="header">
    <%= render 'shared/searchbar' %>
  </div>
  <div class="section-cards">
    <%= render "recipes/recipes", recipes: @recipes, locals: { title: yield(:title) } %>
  </div>
</div>

app/views/meals/show.html.erb
<%- title "Meal Show" %>
<div class="body">
  <div class="section--header">
    <h2>Meal show page: User meal</h1>
    <ul>
      <li><p>User: <%= @user.name_first %></p></li>
      <li><p>Date: <%= @menu.day_of_week %></p></li>
      <li><p>Meal: <%= @meal.meal_type %></p></li>
    </ul>
    <h4>Courses: </h4>
  </div>

  <div class="menu">
    <div class="card-menu-meal__body">
      <%= turbo_frame_tag "meal_#{@meal.id}" do %>
        <%= render @meal %>
      <% end %>
    </div>
  </div>
</div>