config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :households, only: [:show]

  devise_for :users, :path_prefix => 'auth'
  resources :users, except: [:index]

  resources :menus, only: [:index, :show, :new] do
    resources :meals, only: [:show] do
      resources :courses, only: [:destroy]
    end
  end

  resources :menus, only: [] do
    member do
      get ':meal_type', to: 'menus#show_meal', as: 'show_meal'
    end
  end

  resources :courses, only: [:index] do
    collection do
      post 'create', to: 'courses#create', as: 'create'
      delete 'multi_destroy', to: 'courses#multi_destroy', as: 'multi_destroy'
    end
  end

  resources :planners, only: [:index, :new, :create]

  resources :recipes, only: [:index, :show] do
    collection do
      get 'recipe_search'
    end
  end

  resources :fetch_recipes, only: [:index] do
    post 'search'
  end

  resources :groceries, only: [:index, :new, :create] do
    collection do
      patch 'edit_multiple', to: 'groceries#edit_multiple', as: 'edit_multiple'
    end
  end

  # resources :products, only: [:index]
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_household, except: [:create]
  before_action :set_meal_types, only: [:index]
  before_action :set_course_types, only: [:index]
  before_action :set_menu, only: [:destroy]
  before_action :set_meal, only: [:destroy]
  before_action :set_course, only: [:edit, :update, :destroy]

  def index
    course_groups = []
    @meal_ids = params[:meal_ids]
    @meals = params[:meal_ids].map { |id| Meal.find(id) }.flatten
    @meals.each { |meal| course_groups.push(meal.courses.map { |course| Course.find(course.id) }) }
    courses_all = course_groups.flatten
    courses_of_meals = {}
    courses_all.each do |course|
      course_id = course.id
      recipe_id = course.erecipe_id
      if courses_of_meals[recipe_id].nil?
        courses_of_meals[recipe_id] = []
        courses_of_meals[recipe_id].push(course_id)
      else
        courses_of_meals[recipe_id].push(course_id)
      end
    end
    courses_of_meals
    @recipes_with_course_id = courses_of_meals.select { |recipe_id, course_ids| course_ids.count == @meals.size }
    @courses = @recipes_with_course_id.keys.map { |recipe_id| courses_all.detect { |course| course.erecipe_id == recipe_id } }
    @course_recipes = @courses.map { |course| Edamam::EdamamRecipe.find(course.erecipe_id) }
    console
  end

  def create
    courses = Course::Multicourse.create(course_params)
    if courses.count >= 1
      @course = courses.first
      @course_ids = courses.map { |course| course.id }
      respond_to do |format|
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    if params[:query].present?
      @recipes = Edamam::EdamamRecipe.search(params[:query], params[:filters])
    else
      @recipes = Edamam::EdamamRecipe.search("pasta", params[:filters])
    end

    @meal_type = @meal.meal_type
    @course_type = @course.course_type
  end

  def update
    if @course.update(course_params)
      @course.groceries.delete_all
      redirect_to new_grocery_path(course_ids: [@course.id]),
                  notice: "Course successfully updated"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to menu_meal_path(@menu, @meal), notice: "Courses deleted" }
      format.turbo_stream { flash.now[:notice] = "Course deleted" }
    end
  end

  def multi_destroy
    @course = Course.find(params[:course_ids].first.to_i)
    Course.destroy(params[:course_ids])
    meal_ids = params[:meal_ids]
    respond_to do |format|
      # HTML tirggers when cancelling gList#new form
      format.html { redirect_to planners_path(meal_ids: meal_ids), notice: "Canceled, course not added to meal" }
      # Turbo triggers when Course deleted from course#index in sidebar on planner
      format.turbo_stream { flash.now[:notice] = "Course was succesfully removed from meal." }
    end
  end

  private

  def course_params
    params.permit(:course_type, :erecipe_id, meal_ids: [])
  end

  def set_meal_types
    @meal_types = Meal::MEAL_TYPES
  end

  def set_course_types
    @course_types = Course::COURSE_TYPES
  end

  def set_household
    @household = Household.find(current_user.household_id)
  end

  def set_menu
    @menu = Menu.find(params[:menu_id])
  end

  def set_meal
    @meal = @menu.meals.find(params[:meal_id])
  end

  def set_user
    @user = @meal.user
  end

  def set_course
    @course = @meal.courses.find(params[:id])
  end


  # def set_menus
  #   @menus = params[:menu_ids].map { |menu_id| Menu.find(menu_id.to_i) }
  # end

  # def set_users
  #   @users = params[:user_ids].map { |user_id| User.find(user_id.to_i) }
  # end

  # def set_meal_type
  #   @meal_type = params[:meal_type]
  # end
end

app/views/courses/_course.html.erb
<%= turbo_frame_tag dom_id(course), class: "card-course" do %>
    <% recipe = recipes.detect { |recipe| recipe.erecipe_id == course.erecipe_id } %>
  <div class="card-course__header">
    <%= image_tag recipe.recipe_image(size: "thumbnail"), class: "card-course__img" %>
  </div>
  <div class="card-course__details">
      <%= link_to recipe.label, recipe.source_url, :target => '_blank', class: "card-course__recipe-title" %>
  </div>
  <div class="card-course__action">
      <%= button_to "", multi_destroy_courses_path(
                          course_ids: recipe_keyes[course.erecipe_id],
                          meal_ids: @meal_ids),
                        method: :delete,
                        class: "btn btn--stop fa-solid fa-circle-minus",
                        form: {
                            data: {
                              turbo_method: "delete",
                              turbo_confirm: "Delete course?",
                              turbo_confirm_confirm_label: "Yes, delete",
                              turbo_confirm_cancel_label: "Oops ... cancel" } } %>
  </div>
<% end %>

app/views/courses/_form.html.erb
<%= form_with url: create_courses_path do |f| %>
  <%= f.hidden_field :erecipe_id, value: erecipe_id %>
  <%= f.hidden_field :course_type, value: @course_type, data: { target: 'course-new-form.formCourseType' } %>
  <%= f.hidden_field :meal_ids, name:"meal_ids[]", mutliple: true, value: @meal_ids, data: { target: 'course-new-form.formMealIds' } %>
  <%= f.button nil, class:"btn--plus" do %>
    <i class="fa-solid fa-plus"></i>
    <span class="button-text">Add Course</span>
  <% end %>
<% end %>

app/views/courses/create.turbo_stream.erb
<%= turbo_stream.replace "gList" do %>
  <div id="gList">
    <%= turbo_frame_tag dom_id(Grocery.new),
      data: {
        turbo_modal_target: "grocery",
        path: new_grocery_path(course_ids: @course_ids)
      } %>
  </div>
<% end %>

<%= turbo_stream.prepend "flash", partial: "shared/flash" %>

app/views/courses/destroy.turbo_stream.erb
<%= turbo_stream.remove @course %>

<%= turbo_stream.prepend "flash", partial: "shared/flash" %>

app/views/courses/edit.html.erb
<% provide(:title, "Course") %>
<%# <%- title "Course" %> %>
<div class="body">
  <div class="section--header">
    <%= render "shared/searchbar" %>
  </div>
  <div class="section-cards">
    <%= render "recipes/recipes", recipes: @recipes, locals: { title: yield(:title) } %>
  </div>
</div>

app/views/courses/index.html.erb
<%- title "Course Index" %>

<div class="body">

  <%= turbo_frame_tag "courses", class: "section--cards-courses" do %>
      <% unless @course_recipes.nil? %>
        <% @course_types.each do |course_type| %>
          <div class="card-coursetype">
            <span class="card-coursetype__title">
              <h4><%= course_type.capitalize %>:</h4>
            </span>
            <div class="card-coursetype__list">
              <%= render @courses.select { |course| course.course_type == course_type },
                                          recipes: @course_recipes,
                                          recipe_keyes: @recipes_with_course_id %>
            </div>
          </div>
        <% end %>
      <% end %>
  <% end %>

</div>

app/views/courses/multi_destroy.turbo_stream.erb
<%= turbo_stream.replace "gList" do %>
  <div id="gList">
    <%= turbo_frame_tag dom_id(Grocery.new),
      data: {
        turbo_modal_target: "grocery",
        path: new_grocery_path(course_ids: @course_ids)
      } %>
  </div>
<% end %>

<%= turbo_stream.remove @course %>

<%= turbo_stream.prepend "flash", partial: "shared/flash" %>